variable "avz1" {}
variable "avz2" {}
variable "vpc" {}
variable "igw" {}
variable "ngw" {}
variable "eip" {}
variable "pubsn1" {}
variable "pubsn2" {}
variable "prvsn1" {}
variable "prvsn2" {}
variable "pub_rt" {}
variable "prv_rt" {}