variable "red_hat" {} 
variable "nexus_subnet" {}
variable "pub_key" {}
variable "nexus_sg" {}
variable "nexus_name" {}
variable "subnet-elb" {}
#variable "cert-arn" {}
variable "newrelic_api_key" {}
variable "newrelic_account_id" {}
variable "newrelic_region" {}
